### PR TITLE
updated arboretum class to include lists for all biomes

### PR DESCRIPTION
**Pull request by sarahholder**

### CODE REVIEW

**Review by leigharobinson — COMMENTED** [review]
This is Great!

**Comment by christopher7146** [comment]
Awesome!

**Review by leigharobinson — APPROVED** [review]
I Approve!

**Review by kirksudduth — APPROVED** [review]
👍

**Review by christopher7146 — APPROVED** [review]

**Review by tannerb9 — APPROVED** [review]

**Pull request merged**
