### PR TITLE
enabled main level menu to work

### LINKED ISSUE #8: Make 1st lvl menu work

### PR DESCRIPTION
**Pull request by sarahholder**

### CODE REVIEW

**Review by tannerb9 — APPROVED** [review]

**Review by kirksudduth — COMMENTED** [review]
👍

**Review by kirksudduth — APPROVED** [review]
👍

**Review by leigharobinson — APPROVED** [review]
👍

**Comment by christopher7146** [comment]
Looks Great!

**Review by leigharobinson — APPROVED** [review]
👍

**Pull request merged**
